# Generated by Django 4.2.20 on 2025-04-06 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuf_booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingmodel',
            old_name='user',
            new_name='username',
        ),
    ]
