# Generated by Django 4.2.20 on 2025-04-08 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuf_booking', '0002_rename_user_bookingmodel_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingmodel',
            old_name='username',
            new_name='user',
        ),
    ]
